download_url: https://galaxy.ansible.com/download/theforeman-foreman-3.10.0.tar.gz
format_version: 1.0.0
name: foreman
namespace: theforeman
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.10.0
version_url: https://galaxy.ansible.com/api/v2/collections/theforeman/foreman/versions/3.10.0/
