---
- name: Schedule Future Jobs
  hosts: dev
  become: yes
  tasks:
  - name: Show who is logged on and what they are doing at system reboot
    cron:
     name: "System Info"
     special_time: reboot
     job: "w > /tmp/systeminfo.txt"
