---
- name: Schedule Future Jobs
  hosts: dev
  become: yes
  tasks:
  - name: Capture the users login information in /tmp/login.txt file at 2 and 5 hours
    cron:
     name: "Users Login"
     state: absent
