---
- name: Managing the file permissions using ansible
  hosts: dev
  become: yes
  tasks:
  - name: Update modification and access time of the directory 
    file:
     path: /etc/linux
     state: directory
     modification_time: now
     access_time: now
