---
- name: Managing the file permissions using ansible
  hosts: dev
  become: yes
  tasks:
  - name: Create a symbolic link
    file:
     src: /etc/redhat-release
     dest: /tmp/link
     owner: ansible
     group: ansible
     state: link
