---
- name: Managing the file permissions using ansible
  hosts: dev
  become: yes
  tasks:
  - name: Create a directory if it doesnot exist
    file:
     path: /etc/linux
     state: directory
     mode: '0755'
