---
- name: Managing the file permissions using ansible
  hosts: dev
  become: yes
  tasks:
  - name: Touch the smae file, but add/remove some permissions
    file:
     path: /etc/linux.conf
     state: touch
     mode: u+rw,g-wx,o-rwx
