---
- name: Managing Storage Using Ansible Playbook
  hosts: dev
  become: true
  tasks:
  - name: Set/Reset an xfs filesystem UUID on /devxvdf1
    filesystem:
     dev: /dev/xvdf1
     fstype: xfs
     uuid: generate`
