---
- name: Managing Storage Using Ansible Playbook
  hosts: dev
  become: true
  tasks:
  - name: Create a new partition with a size of 1GiB
    parted:
     device: /dev/xvdf
     number: 1
     state: present
     part_end: 1GiB
