---
- name: Managing Storage Using Ansible Playbook
  hosts: dev
  become: true
  tasks:
  - name: Create a new primary partition for LVM
    parted:
     device: /dev/xvdf
     number: 2
     flags: [lvm]
     state: present
     part_start: 1GiB 
