---
- name: Managing Storage Using Ansible Playbook
  hosts: dev
  become: true
  tasks:
  - name: Create First Parttition having GPT label
    parted:
     label: gpt
     state: present
     device: /dev/xvdf
     number: 6
     name: p1
     flags: [lvm]
     part_start: 0%
     part_end: 10%
     unit: '%'
     
