---
- name: Nginx Https Server Configuration in Playbook
  hosts: dev
  become: true
  tasks:
  - name: Setting up the static hostname in the server machine
    hostname:
     name: nginx.local
     use: systemd
  - name: Installing Nginx and OpenSSL packages in the machine
    yum:
     name:
      - nginx
      - openssl 
      - mod_ssl
     state: latest
  - name: Creating the /etc/pki/nginx/private directory for the SSL private key file
    file:
     path: /etc/pki/nginx/private/
     mode: '0755'
     state: directory
  - name: Copying the Nginx configuration file to /etc/nginx directory
    template:
     src: /home/ansible/nginx/nginx.conf.j2
     dest: /etc/nginx/nginx.conf
     force: true
  - name: Generating the private key File with the name as server.key
    openssl_privatekey:
     path: /etc/pki/nginx/private/server.key
     size: 2048
  - name: Generating Certificate Sign Request(CSR)
    community.crypto.x509_certificate:
     path: '/etc/pki/nginx/server.crt'
     privatekey_path: '/etc/pki/nginx/private/server.key'
     force: true
     provider: selfsigned
  - name: Creating the website index file
    copy:
     dest: /usr/share/nginx/html/index.html
     content: |
      <h1>Sandeep is a Devop Engineer</h1>
      <i>This page is hosted on node1 machine using nginx</i>
     force: true
  - name: Starting and Enabling the Nginx Service
    service:
     name: nginx
     state: started
     enabled: yes
