---
- name: Managing users and Groups 
  hosts: dev
  become: yes
  vars:
   password: mySecret
  tasks:
  - name: Adding Simple user called Greta
    user:
     name: greta
     comment: Greta
  
  - name: Add user amit with password 
    user:
     name: amit
     password: "{{ password | password_hash('sha512') }}"
     update_password: on_create

  - name: Add a group called SandeepClasses
    group:
     name: sandeepclasses
     state: present
  
  - name: Add a user Ashish and add them to a group sandeepclasses
    user:
     name: ashish
     groups: sandeepclasses
     append: yes

  - name: Add a user Rahul and generate for them an SSH key
    user:
     name: rahul
     generate_ssh_key: yes
     ssh_key_bits: 2048
     ssh_key_file: .ssh/id_rsa
  
  - name: Add a user noHome with no home and set account to expire on certain date
    user:
     name: noHome
     create_home: no
     expires: 1590155615

  - name: Add a user Suraj having a login shell as sh and add them to a group sandeepclasses
    user:
     name: suraj
     shell: /bin/sh
     groups: sandeepclasses
     append: yes
 
  - name: Add the user 'Vijay Sharma' with specific uid as 1077 having username as vijay, having directory as /home/vijaysharma
    user:
     name: vijay
     comment: Vijay Sharma
     uid: 1077
     create_home: yes
     home: /home/vijaysharma


     













