---
- name: Change SELINUX mode in the configuration file
  hosts: dev
  become: yes
  vars:
   status: permissive
  tasks:
  - name: Changing the SELINUX mode in /etc/selinux/config file
    lineinfile:
     path: /etc/selinux/config
     regexp: '^SELINUX='
     line: 'SELINUX={{ status }}'

