---
- name: Managing the Volume group
  hosts: dev
  become: true
  tasks:
  - name: Create a snapshot volume of the test logical volume 
    lvol:
     vg: sandeep
     lv: test
     snapshot: snap1
     size: 100m
