---
- name: Managing the Volume group
  hosts: dev
  become: true
  tasks:
  - name: Remove logical volume nehraclass
    lvol:
     vg: sandeep
     lv: nehraclass
     state: absent
     force: true
