---
- name: Managing the Volume group
  hosts: dev
  become: true
  tasks:
  - name: Extend the logical volume to consume all remaining space in the volume group
    lvol:
     vg: sandeep
     lv: test
     size: +100%FREE
