---
- name: Relay Mail Server Configuration Using SMTP Playbook
  hosts: dev
  become: true
  tasks:
  - name: Setting up the static hostname in the machine
    hostname:
     name: mail-server.local
     use: systemd
  - name: Installing sendmail packages in the machine 
    yum:
     name:
     - sendmail*
     - procmail
     - s-nail
     - make
     state: latest
  - name: Creating authinfo file in the /etc/mail directory having the authentification information
    template:
     src: /home/ansible/mail/authinfo.j2
     dest: /etc/mail/authinfo
  - name: Copying the sendmail configuration file /etc/mail directory
    template:
     src: /home/ansible/mail/sendmail.mc.j2
     dest: /etc/mail/sendmail.mc
     force: true
  - name: making changes in the sendmail.cf file using m4 processor with the help of sendmail.mc file
    shell: m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf
  - name: Creating encrypted database file(authinfo.db) using authinfo file
    shell: makemap hash /etc/mail/authinfo < /etc/mail/authinfo
  - name: Starting and Enabling the sendmail server
    service:
     name: sendmail
     state: started
     enabled: yes
