---
- name: Yum Repository Management
  hosts: dev
  become: yes
  tasks:
  - name: Install a list of packages
    yum:
     name: 
      - nginx
      - postgresql
      - postgresql-server
     state: present
